---
title: "EDA Project"
subtitle: "Characterizing Opioid Prescriptions and Claims using Provider Information"  
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true

---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE)

library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggridges)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(base_color = "#cc002b")

```

## Hypothesis 1: Opioids That are Prescribed More Frequently are Supplied for Shorter Time Periods
````{r medicare-prec, echo = FALSE, fig.align = 'center', include=TRUE}

#Load Data----
library(tidyverse)
medicare_prescriptions_data <- read_csv("http://www.stat.cmu.edu/cmsac/sure/2022/materials/data/health/eda_projects/medicare_partd_presc_claims.csv")
#Linear graph ?
lineardata <- medicare_prescriptions_data %>%
  filter(OpioidFlag == "Opioid") %>%
  #filter(!is.na(NumberMedicareBeneficiaries))%>%
  filter(NumberDaysSupply <= 20000) 
#Select Drug Names that are prescribed more than 10 times
linear_data2 <- lineardata %>%
  count(GenericName)%>%
  filter(n >10)

lineardata <- lineardata %>%
  filter(GenericName %in% linear_data2$GenericName)
#Bar graph of Drug types
lineardata %>%
  ggplot(aes(x= fct_infreq(GenericName)))+
  geom_bar(stat= "count", fill="darkblue")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+
  coord_flip()+
  labs(title="Which Opioids are Prescribed Most Frequently?",y="# of Prescriptions", x="Drug Type")

```
---
##How Long are Opioids Prescribed?
```{r density, echo = FALSE, fig.align = 'center', include=TRUE}
# Density of Type of Opioid and Number Days Supplied
lineardata %>%
  #library(ggridges)
  ggplot(aes(x = NumberDaysSupply,
             y = fct_infreq(GenericName))) +
  geom_density_ridges(rel_min_height = 0.01) +
  scale_x_continuous(limits = c(1, 20000))+
  theme_bw()+
  labs(y= "Drug Name", x= "# of Days Drug Supplied")


```

---


##Clustering Medicare Drug Prescriptions by Total Cost and Number of Medicare Beneficaries(TX)
````{r cluster, echo = FALSE, fig.align = 'center', include=TRUE}
#Clean Data
Clean_medicare <- medicare_prescriptions_data %>%
  filter(State == "TX", !is.na(TotalDrugCost),!is.na(NumberMedicareBeneficiaries)) %>%
  mutate(log_cost = log(TotalDrugCost), log_benefic = log(NumberMedicareBeneficiaries))%>%
  mutate(std_log_cost = as.numeric(scale(log_cost, center = TRUE, scale = TRUE)),
         std_num_medben = as.numeric(scale(log_benefic, center = TRUE, scale = TRUE)))
#Initial K Means clustering----
init_kmeans <- 
  kmeans(dplyr::select(Clean_medicare,
                       log_cost, NumberMedicareBeneficiaries),
         algorithm = "Lloyd", centers = 4)
#Standardized K Mean Cluster
std_kmeans <- 
  kmeans(dplyr::select(Clean_medicare,
                       std_log_cost, std_num_medben),
         algorithm = "Lloyd", centers = 4)
Clean_medicare %>%
  mutate(cost_clusters = 
           as.factor(std_kmeans$cluster)) %>%
  ggplot(aes(y= std_log_cost, x=std_num_medben, color=cost_clusters)) +
  geom_point(alpha=0.5) + 
  ggthemes::scale_color_colorblind() +
  theme_bw() +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8)) +
  labs(y="Total Cost",x="# of Medicare Beneficaries", color ="Prescription Clusters")+
  coord_fixed()
````
---
##Conlcusion

##Limations
---
class: center, middle

# Thanks!

Slides created via the R packages:

[**xaringan**](https://github.com/yihui/xaringan)<br>
[gadenbuie/xaringanthemer](https://github.com/gadenbuie/xaringanthemer)

The chakra comes from [remark.js](https://remarkjs.com), [**knitr**](http://yihui.name/knitr), and [R Markdown](https://rmarkdown.rstudio.com).
